### ISSUE TITLE
Error plotting images with a `tibble`

### ISSUE THREAD

**Issue by lazappi** [funkyheatmap/funkyheatmap#21]
For some reason image geoms don't work when the data is a `tibble` rather than a `data.frame`. The error seems like the path can't be found (or is the wrong type) but I have no idea why

```r
# Create data
data <- data.frame(
  id = c("Row1", "Row2", "Row3"),
  img = c("images/ice.png", "images/ice.png", "images/electric.png")
)

# Create col info
cols <- data.frame(
  id = c("id", "img"),
  geom = c("text", "image")
)

# This works fine...
funky_heatmap(data, column_info = cols)

# This doesn't for some reason...
funky_heatmap(tibble::as_tibble(data), column_info = cols)
#> Error in magick::image_read(image) : 
#>  path must be URL, filename or raw vector
```

**Comment by rcannood** [comment]
The issue probably arises from tibble not automatically dropping the dimensionality of the data frame when subsetting to just one column. This is a good thing, of course, but different in behaviour from data.frame:

```r
> tibble::tibble(a = 1, b = 2)[,1]
# A tibble: 1 × 1
      a
  <dbl>
1     1
> data.frame(a = 1, b = 2)[,1]
[1] 1
```

Unfortunately I'm having a hard time reproducing this issue with the development version of funkyheatmap. Could it be that the bug was fixed already by accident? Could you confirm whether you can replicate the issue?

**Comment by lazappi** [comment]
Yeah, it seems to be working for me with the latest version of the `main` branch, so it seems like maybe it got fixed somehow.

**Comment by rcannood** [comment]
Alrighty! Thanks for verifying this :)
